name: Pulumify
on: [pull_request, delete]
jobs:
  my_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: Say something
        run: |
          pwd
          cd ./cutemoji
          pwd
          npm install
          pwd
          npm run export