name: Pulumify
on: [pull_request, delete]
jobs:
  previewSiteLive:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out our code
        uses: actions/checkout@master
      - name: Install and build
        run: |
          cd ./cutemoji
          npm install
          npm run export
      - name: Update Live Preview
        uses: docker://pulumi/pulumify
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          PULUMIFY_ROOT: cutemoji/out
